"""status is not unique for every char

Revision ID: 49da53e1929e
Revises: c5c280bca9b1
Create Date: 2024-08-03 16:59:29.992491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49da53e1929e'
down_revision = 'c5c280bca9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recognition_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_user_recognition_progress_status')
        batch_op.create_index(batch_op.f('ix_user_recognition_progress_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recognition_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_recognition_progress_status'))
        batch_op.create_index('ix_user_recognition_progress_status', ['status'], unique=1)

    # ### end Alembic commands ###
