"""empty message

Revision ID: 58a357f754ff
Revises: 
Create Date: 2024-08-31 08:56:22.294129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a357f754ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chinese_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simplified', sa.String(length=8), nullable=False),
    sa.Column('traditional', sa.String(length=8), nullable=False),
    sa.Column('pinyin', sa.String(length=32), nullable=False),
    sa.Column('definition', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chinese_character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chinese_character_definition'), ['definition'], unique=False)
        batch_op.create_index(batch_op.f('ix_chinese_character_pinyin'), ['pinyin'], unique=False)
        batch_op.create_index(batch_op.f('ix_chinese_character_simplified'), ['simplified'], unique=False)
        batch_op.create_index(batch_op.f('ix_chinese_character_traditional'), ['traditional'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('character_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_admin_created', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_list_id'], ['character_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_list_name'), ['name'], unique=False)

    op.create_table('user_meaning_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('memory_strength', sa.Float(), nullable=False),
    sa.Column('last_practice', sa.DateTime(), nullable=False),
    sa.Column('next_practice', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['chinese_character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'character_id', name='unique_user_meaning')
    )
    with op.batch_alter_table('user_meaning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_meaning_progress_status'), ['status'], unique=True)

    op.create_table('user_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['chinese_character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_note_note'), ['note'], unique=False)

    op.create_table('user_pinyin_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('memory_strength', sa.Float(), nullable=False),
    sa.Column('last_practice', sa.DateTime(), nullable=False),
    sa.Column('next_practice', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['chinese_character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'character_id', name='unique_user_pinyin')
    )
    with op.batch_alter_table('user_pinyin_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_pinyin_progress_status'), ['status'], unique=True)

    op.create_table('user_recognition_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('due', sa.DateTime(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('elapsed_days', sa.Integer(), nullable=False),
    sa.Column('scheduled_days', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('last_review', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['chinese_character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'character_id', name='unique_user_recognition')
    )
    op.create_table('user_writing_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('memory_strength', sa.Float(), nullable=False),
    sa.Column('last_practice', sa.DateTime(), nullable=False),
    sa.Column('next_practice', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['chinese_character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'character_id', name='unique_user_writing')
    )
    with op.batch_alter_table('user_writing_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_writing_progress_status'), ['status'], unique=True)

    op.create_table('character_list_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_list_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['chinese_character.id'], ),
    sa.ForeignKeyConstraint(['character_list_id'], ['character_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pinned_character_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_list_id'], ['character_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pinned_character_list')
    op.drop_table('character_list_mapping')
    with op.batch_alter_table('user_writing_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_writing_progress_status'))

    op.drop_table('user_writing_progress')
    op.drop_table('user_recognition_progress')
    with op.batch_alter_table('user_pinyin_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_pinyin_progress_status'))

    op.drop_table('user_pinyin_progress')
    with op.batch_alter_table('user_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_note_note'))

    op.drop_table('user_note')
    with op.batch_alter_table('user_meaning_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_meaning_progress_status'))

    op.drop_table('user_meaning_progress')
    with op.batch_alter_table('character_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_list_name'))

    op.drop_table('character_list')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('chinese_character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chinese_character_traditional'))
        batch_op.drop_index(batch_op.f('ix_chinese_character_simplified'))
        batch_op.drop_index(batch_op.f('ix_chinese_character_pinyin'))
        batch_op.drop_index(batch_op.f('ix_chinese_character_definition'))

    op.drop_table('chinese_character')
    # ### end Alembic commands ###
