"""InitialDesign

Revision ID: c77d50a9bce3
Revises: 
Create Date: 2024-07-25 04:49:15.208275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77d50a9bce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chinese_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(length=1), nullable=False),
    sa.Column('pinyin', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chinese_character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chinese_character_character'), ['character'], unique=True)
        batch_op.create_index(batch_op.f('ix_chinese_character_pinyin'), ['pinyin'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('character_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_admin_created', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_list_id'], ['character_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_list_name'), ['name'], unique=False)

    op.create_table('user_character_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['chinese_character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_character_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_character_status_status'), ['status'], unique=True)

    op.create_table('user_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['chinese_character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_list_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_list_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['chinese_character.id'], ),
    sa.ForeignKeyConstraint(['character_list_id'], ['character_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_list_mapping')
    op.drop_table('user_note')
    with op.batch_alter_table('user_character_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_character_status_status'))

    op.drop_table('user_character_status')
    with op.batch_alter_table('character_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_list_name'))

    op.drop_table('character_list')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('chinese_character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chinese_character_pinyin'))
        batch_op.drop_index(batch_op.f('ix_chinese_character_character'))

    op.drop_table('chinese_character')
    # ### end Alembic commands ###
