"""empty message

Revision ID: fc37ed51858c
Revises: c77d50a9bce3
Create Date: 2024-07-25 13:45:21.540702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc37ed51858c'
down_revision = 'c77d50a9bce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_note_note'), ['note'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_note_note'))

    # ### end Alembic commands ###
